[build]
command = "npm run build"
publish = "dist"

[build.environment]
NODE_VERSION = "18"

# Redirects for SPA
[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[dev]
command = "npm run dev"
port = 8888
targetPort = 3000
